// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XINFERENCE_NET_H
#define XINFERENCE_NET_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xinference_net_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Crtl_bus_BaseAddress;
} XInference_net_Config;
#endif

typedef struct {
    u32 Crtl_bus_BaseAddress;
    u32 IsReady;
} XInference_net;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XInference_net_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XInference_net_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XInference_net_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XInference_net_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XInference_net_Initialize(XInference_net *InstancePtr, u16 DeviceId);
XInference_net_Config* XInference_net_LookupConfig(u16 DeviceId);
int XInference_net_CfgInitialize(XInference_net *InstancePtr, XInference_net_Config *ConfigPtr);
#else
int XInference_net_Initialize(XInference_net *InstancePtr, const char* InstanceName);
int XInference_net_Release(XInference_net *InstancePtr);
#endif

void XInference_net_Start(XInference_net *InstancePtr);
u32 XInference_net_IsDone(XInference_net *InstancePtr);
u32 XInference_net_IsIdle(XInference_net *InstancePtr);
u32 XInference_net_IsReady(XInference_net *InstancePtr);
void XInference_net_EnableAutoRestart(XInference_net *InstancePtr);
void XInference_net_DisableAutoRestart(XInference_net *InstancePtr);

void XInference_net_Set_activation_type(XInference_net *InstancePtr, u32 Data);
u32 XInference_net_Get_activation_type(XInference_net *InstancePtr);

void XInference_net_InterruptGlobalEnable(XInference_net *InstancePtr);
void XInference_net_InterruptGlobalDisable(XInference_net *InstancePtr);
void XInference_net_InterruptEnable(XInference_net *InstancePtr, u32 Mask);
void XInference_net_InterruptDisable(XInference_net *InstancePtr, u32 Mask);
void XInference_net_InterruptClear(XInference_net *InstancePtr, u32 Mask);
u32 XInference_net_InterruptGetEnabled(XInference_net *InstancePtr);
u32 XInference_net_InterruptGetStatus(XInference_net *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
