// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xinference_net.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XInference_net_CfgInitialize(XInference_net *InstancePtr, XInference_net_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Crtl_bus_BaseAddress = ConfigPtr->Crtl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XInference_net_Start(XInference_net *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XInference_net_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_AP_CTRL) & 0x80;
    XInference_net_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XInference_net_IsDone(XInference_net *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XInference_net_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XInference_net_IsIdle(XInference_net *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XInference_net_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XInference_net_IsReady(XInference_net *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XInference_net_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XInference_net_EnableAutoRestart(XInference_net *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XInference_net_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_AP_CTRL, 0x80);
}

void XInference_net_DisableAutoRestart(XInference_net *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XInference_net_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_AP_CTRL, 0);
}

void XInference_net_Set_activation_type(XInference_net *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XInference_net_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_ACTIVATION_TYPE_DATA, Data);
}

u32 XInference_net_Get_activation_type(XInference_net *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XInference_net_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_ACTIVATION_TYPE_DATA);
    return Data;
}

void XInference_net_InterruptGlobalEnable(XInference_net *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XInference_net_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_GIE, 1);
}

void XInference_net_InterruptGlobalDisable(XInference_net *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XInference_net_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_GIE, 0);
}

void XInference_net_InterruptEnable(XInference_net *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XInference_net_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_IER);
    XInference_net_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_IER, Register | Mask);
}

void XInference_net_InterruptDisable(XInference_net *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XInference_net_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_IER);
    XInference_net_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_IER, Register & (~Mask));
}

void XInference_net_InterruptClear(XInference_net *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XInference_net_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_ISR, Mask);
}

u32 XInference_net_InterruptGetEnabled(XInference_net *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XInference_net_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_IER);
}

u32 XInference_net_InterruptGetStatus(XInference_net *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XInference_net_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XINFERENCE_NET_CRTL_BUS_ADDR_ISR);
}

