// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xinference_net.h"

extern XInference_net_Config XInference_net_ConfigTable[];

XInference_net_Config *XInference_net_LookupConfig(u16 DeviceId) {
	XInference_net_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XINFERENCE_NET_NUM_INSTANCES; Index++) {
		if (XInference_net_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XInference_net_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XInference_net_Initialize(XInference_net *InstancePtr, u16 DeviceId) {
	XInference_net_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XInference_net_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XInference_net_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

